name: FTC Robot Controller CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout team code
      uses: actions/checkout@v4
    - name: Update FTC Robot Controller
      run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git remote add FtcRobotController https://github.com/FIRST-Tech-Challenge/FtcRobotController
        git fetch FtcRobotController
        git merge --squash --allow-unrelated-histories -X ours FtcRobotController/master

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
